version: '3'
services:
  web:
    build: .
    command: npm run dev
    environment:
      MONGO_URI: mongodb://mongo/focustas
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
    links:
        - mongo
    depends_on:
        - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
